[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "pyoptinterface"
version = "0.0.1"
description = "Python interface to multiple optimization solvers"
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.8"
authors = [{ name = "Yue Yang", email = "metab0t@outlook.com" },
]
classifiers = []

[project.urls]
Homepage = "https://github.com/metab0t/pyoptinterface"

[project.optional-dependencies]
doc = ["sphinx", "myst-parser", "sphinx-copybutton", "furo"]
test = ["pytest", "numpy"]

[tool.scikit-build]
editable.rebuild = true
build-dir = "build/{wheel_tag}"
cmake.build-type = "Release"

[tool.scikit-build.cmake.define]
ENABLE_GUROBI_CXX = "OFF"
PYTHON_VERSION = {env="PYTHON_VERSION", default="3.8"}
CMAKE_FIND_DEBUG_MODE = "OFF"
