[build-system]
requires = ["scikit-build-core", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "pyoptinterface_nb"
version = "0.0.1"
description = "An example minimal project that compiles bindings using nanobind and scikit-build"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "John", email = "john@gmail.com" },
]
classifiers = [
]

[project.urls]
Homepage = "https://github.com/wjakob/nanobind_example"

[tool.scikit-build]
editable.rebuild = true
build-dir = "build/{wheel_tag}"

[tool.scikit-build.cmake.define]
ENABLE_GUROBI_CXX = "OFF"
