name: windows-build

on:
    pull_request:
    push:
        branches:
            - master
        tags:
          - '*'

jobs:

  windows_build:
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: ./.github/actions/setup_optimizers_windows
        with:
          GUROBI_WLS: ${{ secrets.GUROBI_WLS }}
          COPT_CLIENT_INI: ${{ secrets.COPT_CLIENT_INI }}
          MOSEK_LICENSE: ${{ secrets.MOSEK_LICENSE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_LICENSE: true

      - name: Install python deps
        run: |
          python -m pip install pytest numpy

      - name: Build
        run: |
          python -m pip list
          python -m pip install -v .
          python -c "import pyoptinterface as poi; print(dir(poi))"

      - name: Test
        run: |
          python -m pytest tests -v -k "not copt"
